image: hipay/gitlab-ci-base:jessie

variables:
  PORT_WEB: 80
  PROJECT_NAME_TEST_MG2_1: ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}-1
  PROJECT_NAME_TEST_MG2_2: ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}-2

stages:
 - sync


sync:
  stage: sync
  script:
  - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-fullservice-sdk-magento2.git
  - cd hipay-fullservice-sdk-magento2.git
  - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-fullservice-sdk-magento2.git
  allow_failure: true
