magento2:
  container_name: magento2-hipay-fullservice
  dockerfile: ./conf/docker/Dockerfile
  build: .
  ports:
    - "8080:80"
  links:
    - db
    - smtp
db:
  container_name: magento2-hipay-mysql
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
smtp:
  container_name: magento2-hipay-smtp
  image: schickling/mailcatcher
  ports:
    - "1081:1080"

