magento2:
  image: sirateck/devops-magento2
  ports:
    - "8080:80"
  links:
    - db
    - selenium
  env_file:
    - env/auth.env
    - env/mage.env
    - env/module.env
db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
selenium:
  image: selenium/standalone-firefox
