magento2:
  ports:
    - "4444"
  links:
    - selenium
  env_file:
    - ./conf/env/mage.env.stage
    - ./conf/env/module.env.stage
selenium:
  image: selenium/standalone-firefox
  ports:
    - "4444:4444"
