magento2:
  env_file:
    - ./bin/conf/development/mage.env.sample
    - ./bin/conf/development/auth.env
    - ./bin/conf/development/module.env.sample
    - ./bin/conf/development/hipay.env
  ports:
    - "8080:80"
  volumes:
    - ./:/var/www/html/magento2/app/code/HiPay/FullserviceMagento
    - ./tests:/var/www/html/magento2/tests
    - ./log:/home/magento2/var/log
    - ./conf/sdk:/var/www/html/magento2/sdk
db:
  ports:
    - "3308:3306"
  volumes:
    - ./data/mysql:/var/lib/mysql

