magento2:
    container_name: jira-mg2tpp-develop.hipay-pos-platform.com
  ports:
    - "80:80"
  links:
    - db
    - selenium
  env_file:
    - ./conf/stage/hipay.env.sample
    - ./conf/stage/auth.env.sample
    - ./conf/stage/mage.env.sample
    - ./conf/stage/module.env.sample
selenium:
  image: selenium/standalone-firefox
  ports:
    - "4444:4444"
smtp:
  container_name: magento2-hipay-smtp
  ports:
    - "1081:1080"
